version: '3'

services:
  with-docker-multi-env-development:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: with-docker-multi-env-development
    ports:
      - "3000:3000"
    environment:
      - VIRTUAL_HOST=${HOST:-localhost}
      - VIRTUAL_PORT=3000
      - VIRTUAL_PATH=/
    networks:
      - production_proxy-network

networks:
  production_proxy-network:
    external: true