version: '3'

services:
  nginx:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${XDG_RUNTIME_DIR:-/var/run}/docker.sock:/tmp/docker.sock:ro"
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs
      - share:/usr/share/nginx/html
networks:
  port-proxy:
    name: dinosaur
    external: true

  certbot:
    restart: always
    image: nginxproxy/acme-companion:latest
    container_name: certbot
    volumes_from:
      - nginx
    volumes:
      - "${XDG_RUNTIME_DIR:-/var/run}/docker.sock:/var/run/docker.sock:ro"
      - acme:/etc/adme.sh
    networks:
      - proxy-network
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}

volumes:
  vhost:
  share:
  certs:
  acme:

networks:
  proxy-network:
