version: '3'

services:
  frontend:
    image: ghcr.io/tropicode-guam/blue-guam:${TAG:-main}
    environment:
      - VIRTUAL_HOST=${HOST}
      - LETSENCRYPT_HOST=${HOST}
      - VIRTUAL_PORT=3000
      - VIRTUAL_PATH=/
    networks:
      - production_proxy-network

networks:
  production_proxy-network:
    external: true